version: "{build} ~ {branch}"

os: Visual Studio 2017

environment:
  matrix:
    - CHANNEL: stable
      ARCH: x86_64
      ABI: msvc
      TARGET: x86_64-pc-windows-msvc

install:
  # Install LLVM
  - mkdir C:\projects\deps
  - mkdir C:\projects\deps\llvm-7.0.1-build-dir
  - mkdir C:\projects\deps\llvm-7.0.1-install
  - cd C:\projects\deps
  - appveyor DownloadFile http://releases.llvm.org/7.0.1/llvm-7.0.1.src.tar.xz -FileName llvm-7.0.1.src.tar.xz
  - 7z x llvm-7.0.1.src.tar.xz -oC:\projects\deps\llvm-7.0.1-src
  - cd C:\projects\deps\llvm-7.0.1-build-dir
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="C:\projects\deps\llvm-7.0.1-install" -DLLVM_TARGETS_TO_BUILD="x86" -Thost=x64 C:\projects\deps\llvm-7.0.1-src
  - cmake --build . --config Release --target INSTALL
  - set "LLVM_SYS_70_PREFIX=C:\projects\deps\llvm-7.0.1-install"
  - cd "%APPVEYOR_BUILD_FOLDER%"

  build_script:
   - echo build complete